# Generated by Django 3.1.4 on 2020-12-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.JSONField()),
                ('phone', models.TextField()),
                ('website', models.TextField()),
                ('company', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='downloader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.TextField(blank=True, default=None, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='taks.user')),
            ],
        ),
    ]
