# Generated by Django 3.1.4 on 2020-12-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taks', '0002_downloader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(),
        ),
    ]
